/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "echo.h"
#include<sys/socket.h>
#include<sys/types.h>
#include<netinet/in.h>
#include<string.h>
#include<stdio.h>
#include<pthread.h>



void *echo_server(void *port1)
{
	int *port,n;
	int sockfd,peerfd;
	char buf[256];
	struct sockaddr_in serv_addr,peer_addr;
	socklen_t peer_len;
	
	printf("\n In thread");
	if((sockfd = socket(AF_INET,SOCK_STREAM,0))==-1)
		printf("\nerror in creating socket");
	
	port = (int *)port1;
	printf("\nport : %d",*port);
	
	bzero((char *)&serv_addr,sizeof(serv_addr));
	serv_addr.sin_family=AF_INET;
	serv_addr.sin_port=htons(*port);
	serv_addr.sin_addr.s_addr=INADDR_ANY;
	if(bind(sockfd,(struct sockaddr *)&serv_addr,sizeof(serv_addr))==-1)
		printf("\nerror in binding socket");
	listen(sockfd,5);	
	peer_len = sizeof(peer_addr);
	printf("\nWaiting for client to get connected...");
	if((peerfd = accept(sockfd,(struct sockaddr *)&peer_addr,&peer_len))==-1)
		printf("\nerror in accepting connection");
	
	printf("\nrecieving message");
	//do
    //{
    	bzero(buf,255);
        //***newsockfd returned from accept 
        n = recv(peerfd,buf,255,0);
        if(n<0)  
        	printf("\nerror in receiving message from client");
        else 
        	printf("\nmessage received :%s",buf);
        if(send(peerfd,buf,255,0)==-1)
            printf("error in sending msg to client");
	//}while(strcmp(buf,"exit\n"));
	close(sockfd);
}
int *echo_1_svc(int *port, struct svc_req *rqstp)
{
	static int result;
	pthread_t t;
	pthread_create(&t,NULL,echo_server,(void *)port);
	
	printf("\nPORT : %d",*port);
	result = 4;
	return  &result;
}
