/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ECHO_H_RPCGEN
#define _ECHO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define PROG 123
#define VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define echo 12
extern  int * echo_1(int *, CLIENT *);
extern  int * echo_1_svc(int *, struct svc_req *);
extern int prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define echo 12
extern  int * echo_1();
extern  int * echo_1_svc();
extern int prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ECHO_H_RPCGEN */
