/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "echo.h"


void
prog_1(char *host)
{
	CLIENT *clnt;
	int  *result;
	int  port = 10005;

#ifndef	DEBUG
	clnt = clnt_create (host, PROG, VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result = echo_1(&port, clnt);
	if (result == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("%d",*result);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	prog_1 (host);
exit (0);
}
