/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AVG_H_RPCGEN
#define _AVG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXSIZE 50

struct numlist {
	int num[MAXSIZE];
	int len;
};
typedef struct numlist numlist;


#define SQRPROGRAM 123
#define SQRVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define sqr 12
extern  double * sqr_1(numlist *, CLIENT *);
extern  double * sqr_1_svc(numlist *, struct svc_req *);
extern int sqrprogram_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sqr 12
extern  double * sqr_1();
extern  double * sqr_1_svc();
extern int sqrprogram_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numlist (XDR *, numlist*);
extern  bool_t xdr_numlist (XDR *, numlist*);

#else /* K&R C */
extern bool_t xdr_numlist ();
extern bool_t xdr_numlist ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AVG_H_RPCGEN */
