/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SQR_H_RPCGEN
#define _SQR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define SQRPROGRAM 123
#define SQRVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define sqr 12
extern  double * sqr_1(double *, CLIENT *);
extern  double * sqr_1_svc(double *, struct svc_req *);
extern int sqrprogram_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sqr 12
extern  double * sqr_1();
extern  double * sqr_1_svc();
extern int sqrprogram_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SQR_H_RPCGEN */
