/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _IDLE_H_RPCGEN
#define _IDLE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct twono {
	int num1;
	int num2;
};
typedef struct twono twono;

#define IDLE 123
#define VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define getcpu 12
extern  float * getcpu_1(void *, CLIENT *);
extern  float * getcpu_1_svc(void *, struct svc_req *);
#define add 13
extern  int * add_1(struct twono *, CLIENT *);
extern  int * add_1_svc(struct twono *, struct svc_req *);
extern int idle_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getcpu 12
extern  float * getcpu_1();
extern  float * getcpu_1_svc();
#define add 13
extern  int * add_1();
extern  int * add_1_svc();
extern int idle_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_twono (XDR *, twono*);

#else /* K&R C */
extern bool_t xdr_twono ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_IDLE_H_RPCGEN */
